import { SessionProvider } from "next-auth/react"
import TutorLayout from "../layout/TutorLayout";
import DirectivoLayout from "../layout/DirectivoLayout";
import ProfesorLayout from "../layout/ProfesorLayout";

import "global.styles.css";
import { CookiesProvider } from 'react-cookie';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}


export const AppContext = ({ Layout, pageProps, session, Component }) => {
    return (
        <CookiesProvider>
            <main className="bg-secondary">
                <SessionProvider session={session}>
                    {
                        Layout ? <Layout {...pageProps}>
                            <Component {...pageProps} />
                        </Layout>
                            : <Component {...pageProps} />
                    }

                </SessionProvider>
            </main>
        </CookiesProvider>
    )
}

export default function App(
    { Component, pageProps: { session, ...pageProps }, ...appProps }) {
    const pathname = appProps.router.pathname;

    if ([`/auth/login`].includes(pathname) || [`/auth/loginEmail`].includes(pathname))
        return <Component {...pageProps} />;
    if (pathname.startsWith("/student"))
        return (AppContext({ Layout: TutorLayout, pageProps, session, Component }))
    if (pathname.startsWith("/directive"))
        return (AppContext({ Layout: DirectivoLayout, pageProps, session, Component }))
    if (pathname.startsWith("/professor"))
        return (AppContext({ Layout: ProfesorLayout, pageProps, session, Component }))
    // check if is "/" route    
    if (pathname === "/")
        return (AppContext({ Layout: null, pageProps, session, Component }))
    else
        return (
            <>
                <main className="bg-secondary">
                    Error 404
                </main>
            </>
        )
}