import { SessionProvider } from "next-auth/react"
import DafaultLayout from "../layout/DefaultLayout";
import "global.styles.css";
export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function App({
    Component,
    pageProps: { session, ...pageProps },
}) {
    return (
        <>
            <main className="bg-secondary">
                <DafaultLayout>
                    <SessionProvider session={session}>
                        <Component {...pageProps} />
                    </SessionProvider>

                </DafaultLayout>
            </main>
        </>
    )
}