import { SessionProvider } from "next-auth/react"
import DafaultLayout from "../layout/DefaultLayout";
import "global.styles.css";
import { CookiesProvider } from 'react-cookie';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function App(
    { Component, pageProps: { session, ...pageProps }, ...appProps }) {
    if ([`/auth/login`].includes(appProps.router.pathname) || [`/auth/loginEmail`].includes(appProps.router.pathname))
        return <Component {...pageProps} />;
    return (
        <>
            <CookiesProvider>
                <main className="bg-secondary">
                    <DafaultLayout>
                        <SessionProvider session={session}>
                            <Component {...pageProps} />
                        </SessionProvider>
                    </DafaultLayout>
                </main>
            </CookiesProvider>
        </>
    )
}